### ISSUE TITLE
Channel switching

### ISSUE THREAD

**Issue by pizzapim** [fhunleth/midi_synth#6]
What do you think about adding functionality to switch MIDI channels?
It's possible using MIDISynth.midi/2 but I see that functions in MIDISynth.Command are hardcoded with channel 0.

**Comment by fhunleth** [comment]
I like it. That was an oversight that I ended up not fixing since I didn't need it for my use. It definitely needs to be fixed, though.

If you want to add it, I'd take the PR. Or if you want to copy/paste the functions in your code, experiment with it a bit to see what you like and then come back, that works too.

**Comment by fhunleth** [comment]
Fixed in #7
